Final project - Front end
2bleO/final-group-capstone-frontend pull request #23
Opened 2022-01-21 07:50 UTC by sheylaPozo

Our project was created in two repositories and this is the front-end repo created with React and Redux.
This project is a flat rental app that allows a logged-in user to view available flats, add a new flat, delete a car, and reserve a flat.
Data is gotten from the backend API also created by our team
We shared each task according to the strengths of every teammate
We also shared each task fairly to ensure no one does more work than the other.
Components:
Splash - This component represents our splash page. This is the root page of the project if a user is not login. In there a user has the possibility to login or signup to be able to use the application.

SignUp - This component represents our signup page. Here the user is able to create an account to use the application.

Login - This component represents our login page. Here the user is able to log in with his account (username) to the application.

App - In this component finds all the routes for this project, that are used to navigate a user to different pages of the project.

HomePage - This is the main page of the project after a user is login. Here you can see all the cars that are fetched from the API. If a user clicks on a specific car is redirected to the Details page.

Details - this is a page where a user can see all the details for a specific car, that he choose from the main page.

Add onClick event, that calls a goToReservePage function. To the function itself is passed currentFlat object. The function redirects the user to the Reserve page and passes the object to it.
AddItem:

Create form: onChange event of the inputs is setting the values of parameters after a user types, that are passed to a createFlat function.
Create CreateFlat function that sent data (object car) to the API, using post method. A new item is added to the database. After successfully posting the request to the API action with the newly created object car passed is dispatched. The reducer updated the state and it is stored.
Reserve component:

loadCities function is used to fetch all the cities from the API. The function is called in useEffect method, so the cities can be reloaded on change. The cities are used in a form, where users can select a city from a drop-down menu, in order to create a reservation.
The name of the car, that the user wants to reserve is auto-filled.
The data filled in in the form
is sent to set the state. And when is submitted action is dispatched
with the necessary parameters.
DeleteItem: - Here a user is able to delete a car from the database. It happens by the use of a delete request to the API.

My reservations: A user can see all the reservations he made. An API request is made to get all the reservations for a current user.

Contributions:
@2bleO 
@sheylaPozo 

Kindly take a look at our project 🙏🏽
Thank you 😁

2022-01-21 12:36 UTC, MuriloRoque requested changes
Hi @sheylaPozo, @2bleO, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:

- [ ] Adding tests would be great.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-21 12:36 UTC, MuriloRoque commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
- [ ] **(OPTIONAL)** Adding a personalized icon would be cool.

2022-01-21 12:36 UTC, MuriloRoque commented on public/index.html
> +    <title>React App</title>
- [ ] **(OPTIONAL)** Adding a personalized title would be cool.

2022-01-21 12:36 UTC, MuriloRoque commented on src/App.js
> +        <Route path="/flats" exact element={<HomePage />} />
- [ ] Unless I am missing something, I don't see a reason to use two paths for the same component.

2022-01-21 12:36 UTC, MuriloRoque commented on src/components/DeleteItem/DeleteItem.js
> +          alert("Apartment Deleted");
- [ ] I wouldn't use `alert` here for the same reason I avoid `console.log`, it isn't a good practice. Instead, it would be better to create a modal component with the confirmations/pop-ups. There are a lot of libraries that do this if you think it would be easier.

2022-01-21 12:36 UTC, MuriloRoque commented on src/components/DeleteItem/DeleteItem.js
> +    console.log(e.target.value);
- [ ] Same thing here, using `console.log` isn't a good practice, unless you are only making tests during development.

2022-01-21 12:36 UTC, MuriloRoque commented on src/components/Reservation/Reservation.jsx
> +  };
- [ ] Adding a validation for `start_date` and `end_date` here would be great, currently I could add a `start_date` bigger than an `end_date`.

2022-01-21 12:36 UTC, MuriloRoque commented on src/components/Reserve/Reserve.jsx
> +}
- [ ] **(OPTIONAL)** Since you did it this way (created two components `Reserve` and `Reservation`), I advise you to at least re-utilize the code, since both are almost the same. Maybe create a component with the common code and then just render it inside of them? This may also become too complicated and worse, so you might think it's not worth it anyway.

2022-01-22 00:42 UTC, MuriloRoque approved these changes
Hi @sheylaPozo, @2bleO, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-01-22 00:45 UTC, merged

2022-01-22 00:45 UTC, sheylaPozo commented
thank youu